// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace Nomes.Web.API.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220814213210_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrincipalNameIndex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SearchTabIndex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Emoji = "🏆",
                            PrincipalNameIndex = "0",
                            SearchTabIndex = "2",
                            Titulo = "Populares"
                        },
                        new
                        {
                            Id = 2,
                            Emoji = "🔥",
                            PrincipalNameIndex = "6",
                            SearchTabIndex = "4",
                            Titulo = "Ascenção"
                        },
                        new
                        {
                            Id = 3,
                            Emoji = "⭐",
                            PrincipalNameIndex = "4",
                            SearchTabIndex = "3",
                            Titulo = "Diferentes"
                        },
                        new
                        {
                            Id = 4,
                            Emoji = "⚽",
                            PrincipalNameIndex = "1",
                            SearchTabIndex = "5",
                            Titulo = "Futebol"
                        },
                        new
                        {
                            Id = 5,
                            Emoji = "✨",
                            PrincipalNameIndex = "2",
                            SearchTabIndex = "6",
                            Titulo = "Famosos"
                        },
                        new
                        {
                            Id = 6,
                            Emoji = "🪐",
                            PrincipalNameIndex = "3",
                            SearchTabIndex = "7",
                            Titulo = "Astronomia"
                        },
                        new
                        {
                            Id = 7,
                            Emoji = "🧘‍♀️",
                            PrincipalNameIndex = "4",
                            SearchTabIndex = "8",
                            Titulo = "Pensadores"
                        },
                        new
                        {
                            Id = 8,
                            Emoji = "🦸‍♂️",
                            PrincipalNameIndex = "5",
                            SearchTabIndex = "9",
                            Titulo = "Geeks"
                        });
                });

            modelBuilder.Entity("Models.VisitaCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("VisitaCategorias");
                });

            modelBuilder.Entity("Models.VisitaNome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("VisitaNomes");
                });
#pragma warning restore 612, 618
        }
    }
}
